Merging joining and concatinating

In [1]:
import numpy as np
import pandas as pd

In [3]:
var1 = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]},index=["A","B","C","d"])
var2 = pd.DataFrame({"C":[9,10,11],"D":[13,14,15]})

In [8]:
pd.concat([var1,var2],axis=1)

     A    B     C     D
A  1.0  5.0   NaN   NaN
B  2.0  6.0   NaN   NaN
C  3.0  7.0   NaN   NaN
d  4.0  8.0   NaN   NaN
0  NaN  NaN   9.0  13.0
1  NaN  NaN  10.0  14.0
2  NaN  NaN  11.0  15.0

In [13]:
var1.join(var2,how='left')

   A  B   C   D
A  1  5 NaN NaN
B  2  6 NaN NaN
C  3  7 NaN NaN
d  4  8 NaN NaN

In [14]:
var1.join(var2,how='right')

    A   B   C   D
0 NaN NaN   9  13
1 NaN NaN  10  14
2 NaN NaN  11  15

Group by aggregation

In [19]:
data ={
    'Categeory':['A','B','A','B','A','A','B','A'],
    'Store':['S1','S2','S1','S1','S2','S2','S1','S2'],
    'Quantity':[100,200,150,250,120,180,200,300],
    'Date':pd.date_range('10/04/2026',periods=8)
}
df =pd.DataFrame(data)
df

  Categeory Store  Quantity       Date
0         A    S1       100 2026-10-04
1         B    S2       200 2026-10-05
2         A    S1       150 2026-10-06
3         B    S1       250 2026-10-07
4         A    S2       120 2026-10-08
5         A    S2       180 2026-10-09
6         B    S1       200 2026-10-10
7         A    S2       300 2026-10-11

In [21]:
#Group by category and calcualate the sum of sales 
df.groupby('Categeory')['Quantity'].sum()

Categeory
A    850
B    650
Name: Quantity, dtype: int64

In [22]:
#Group by Store and Calcualate the sum of Quantitydf.
df.groupby("Store")['Quantity'].sum()

Store
S1    700
S2    800
Name: Quantity, dtype: int64

In [25]:
#Group by multiple Column
df.groupby(['Categeory','Store'])["Quantity"].sum()

Categeory  Store
A          S1       250
           S2       600
B          S1       450
           S2       200
Name: Quantity, dtype: int64

Aggregation

In [26]:
df["Quantity"].mean()

np.float64(187.5)

In [27]:
df["Quantity"].median()

np.float64(190.0)

In [30]:
df["Quantity"].agg(['mean','max','min','median','count','sum'])

mean       187.5
max        300.0
min        100.0
median     190.0
count        8.0
sum       1500.0
Name: Quantity, dtype: float64